import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 폰트 변수를 body의 className 뒤에 띄어쓰기로 안전하게 결합했습니다. */}
      <body 
        className={`min-h-full flex flex-col ${geistSans.variable} ${geistMono.variable}`} 
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}